TeamWork/Controllers/DirectoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TeamWork.Controllers.Base;
using TeamWork.Infrastructure.Model;

namespace TeamWork.Controllers
{
    public class DirectoryController : BaseController
    {
        //
        // GET: /Directory/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UserRole()
        {
            var model = RoleService.GetRoles();

            return View(model);
        }

        public ActionResult AddNewRole(RoleDto item)
        {
            if (TryValidateModel(item))
            {
                RoleService.InsertRole(item);
            }

            return RedirectToAction("UserRole");
        }

        [HttpPost]
        public ActionResult EditRole(int roleId)
        {
            var model = RoleService.GetRole(roleId);
            return View(model);
        }

        [HttpPost]
        public ActionResult EditRole(RoleDto item)
        {
            if (TryValidateModel(item))
            {
                RoleService.UpdateRole(item);
                return RedirectToAction("UserRole");
            }

            return View(item);
        }

     
    }
}

TeamWork/Views/Directory/EditRole.cshtml
@model TeamWork.Infrastructure.Model.RoleDto

@{
    ViewBag.Title = "EditRole";
}

<h2>EditRole</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        @Html.HiddenFor(model => model.RoleId)

        <div class="editor-label">
            @Html.LabelFor(model => model.RoleName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RoleName)
            @Html.ValidationMessageFor(model => model.RoleName)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "UserRole")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TeamWork/Views/Directory/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<div class="row">
    <div class="col-lg-6">
        <ul>
            <li>@Html.ActionLink("Role", "UserRole")</li>
        </ul>
    </div>
</div>

TeamWork/Views/Directory/UserRole.cshtml
@model IEnumerable<TeamWork.Infrastructure.Model.RoleDto>

@{
    ViewBag.Title = "UserRole";
}

<h2>User Role</h2>

<p>
    @Html.ActionLink("Create New", "AddNewRole")
</p>

@using(Html.BeginForm("AddNewRole", "Directory", FormMethod.Post))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <div class="editor-label">
            <label for="RoleName">Role name</label>
        </div>
        <div class="editor-field">
            <input id="RoleName" name="RoleName" value="" type="text" />
        </div>
        <p>
            <input type="submit" value="Add new role" />
        </p>
    </fieldset>
}


<table class="table table-striped">
    <tr>
 
        <th>
            @Html.DisplayNameFor(model => model.RoleName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
 
            <td>
                @Html.DisplayFor(modelItem => item.RoleName)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditRole", new { id=item.RoleId})  
            </td>
        </tr>
    }

</table>

 